# Generated by Django 3.0.5 on 2020-05-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('game', models.CharField(max_length=100)),
                ('max_players', models.IntegerField()),
                ('reserved_players', models.IntegerField()),
            ],
        ),
    ]
