import { Party } from './party';

export const Parties: Party[] = [
  { id: 11,   
    owner: 'PhantomLion',
    created: new Date(),
    title: 'Search & Destroy',
    description: 'Looking for God Squad!',
    game: 'Call of Duty Modern Warfare',
    maxPlayers: 6,
    reservedPlayers: 3,
    members: [] },
  { id: 12, 
    owner: 'CrookedSharpshooter',
    created: new Date(),
    title: 'Legendary Difficulty',
    description: 'Play through campaign.',
    game: 'Halo 3',
    maxPlayers: 4,
    reservedPlayers: 1,
    members: [] },
  { id: 13, 
    owner: 'TransonicMosquito',
    created: new Date(),
    title: 'Tournament',
    description: 'Need players with good communication.',
    game: 'Rocket League',
    maxPlayers: 4,
    reservedPlayers: 3,
    members: [] },
  { id: 14, 
    owner: 'WickedAtom',
    created: new Date(),
    title: 'Leviathan Raid',
    description: 'I need a full fireteam.',
    game: 'Destiny 2',
    maxPlayers: 6,
    reservedPlayers: 2,
    members: [] },
  { id: 15, 
    owner: 'ThermionicFrog',
    created: new Date(),
    title: 'Achievement Hunter',
    description: 'Need squad for Achievements.',
    game: '7 Days to Die',
    maxPlayers: 4,
    reservedPlayers: 3,
    members: [] }
];