# Generated by Django 3.0.6 on 2020-05-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamFinder', '0002_auto_20200504_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
