# Generated by Django 3.0.5 on 2020-05-04 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamFinder', '0003_auto_20200504_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
